Build for macOS 10.10
Since both pwsafe & wxWidgets 3.0.5 will compile for macOS 10.9 but fail
to link with this error:

Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      wxPipeInputStream::CanRead() const in libwx_baseu-3.0.a(baselib_utilsunx.o)
      wxSelectSets::HasFD(int) const in libwx_baseu-3.0.a(baselib_selectdispatcher.o)
      wxSelectSets::SetFD(int, int) in libwx_baseu-3.0.a(baselib_selectdispatcher.o)
      wxSelectSets::Handle(int, wxFDIOHandler&) const in libwx_baseu-3.0.a(baselib_selectdispatcher.o)
      wxSelectDispatcher::UnregisterFD(int) in libwx_baseu-3.0.a(baselib_selectdispatcher.o)
      wxSelectDispatcher::ProcessSets(wxSelectSets const&) in libwx_baseu-3.0.a(baselib_selectdispatcher.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)